# Generated by Django 6.0.1 on 2026-02-06 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_label', models.IntegerField()),
                ('recommended_products', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'segment_label')},
            },
        ),
    ]
